import { SampleQuestion } from "./types"

export const randomQuestions = [
	{
		q: "Hovedsteder som begynner på bokstaven 'B'",
		a: [
			"Bagdad",
			"Baku",
			"Bamako",
			"Bandar Seri Begawan",
			"Bangkok",
			"Bangui",
			"Banjul",
			"Basseterre",
			"Beijing",
			"Beirut",
			"Beograd",
			"Belmopan",
			"Berlin",
			"Bern",
			"Bisjkek",
			"Bissau",
			"Bogota",
			"Brasilia",
			"Bratislava",
			"Brazzaville",
			"Bridgetown",
			"Brussel",
			"Bucuresti",
			"Budapest",
			"Buenos Aires",
			"Bujumbura",
		],
	},
	{
		q: "Statsministere i Norge etter krigen",
		a: [
			"Einar Gerhardsen",
			"Oscar Torp",
			"John Lyng",
			"Per Borten",
			"Trygve Bratteli",
			"Lars Korvald",
			"Odvar Nordli",
			"Gro Harlem Brundtland",
			"Kåre Willoch",
			"Jan P. Syse",
			"Thorbjørn Jagland",
			"Kjell Magne Bondevik",
			"Jens Stoltenberg",
			"Erna Solberg",
			"Jonas Gahr Støre",
		],
	},
	{
		q: "Top 25 filmer på IMDb",
		a: [
			"The Shawshank Redemption",
			"The Godfather",
			"The Dark Knight",
			"The Godfather Part II",
			"12 Angry Men",
			"Schindler's List",
			"The Lord of the Rings: The Return of the King",
			"Pulp Fiction",
			"The Good, the Bad and the Ugly",
			"The Lord of the Rings: The Fellowship of the Ring",
			"Fight Club",
			"Forrest Gump",
			"Inception",
			"The Lord of the Rings: The Two Towers",
			"Star Wars: Episode V - The Empire Strikes Back",
			"The Matrix",
			"Goodfellas",
			"One Flew Over the Cuckoo's Nest",
			"Se7en",
			"Seven Samurai",
			"It's a Wonderful Life",
			"The Silence of the Lambs",
			"Saving Private Ryan",
			"City of God",
			"Life Is Beautiful",
		],
	},
	{
		q: "Land som grenser til Østerrike",
		a: [
			"Tyskland",
			"Tsjekkia",
			"Slovakia",
			"Ungarn",
			"Slovenia",
			"Italia",
			"Sveits",
			"Liechtenstein",
		],
	},
	{
		q: "Land på 4 bokstaver",
		a: [
			"Nieu",
			"Cuba",
			"Fiji",
			"Iran",
			"Irak",
			"Laos",
			"Mali",
			"Oman",
			"Peru",
			"Togo",
		],
	},
	{
		q: "Twist",
		a: [
			"Daim",
			"Japp",
			"Banan",
			"Aprikos",
			"Lakris",
			"Caramel",
			"Nougat Crisp",
			"Nøtti",
			"Golden Toffee",
			"Marsipan",
			"Fransk nougat",
			"Cocos",
			"Chocolate Toffee",
		],
	},
	{
		q: "Medlemmer fra ABBA eller Beatles",
		a: [
			"Anni-Frid",
			"Agneta",
			"Bjørn",
			"Benny",
			"Ringo",
			"John",
			"Paul",
			"George",
		],
	},
	{
		q: "Jordens 10 største innsjøer",
		a: [
			"Kaspiske hav",
			"Superior-sjøen",
			"Victoria-sjøen",
			"Huron-sjøen",
			"Michigan-sjøen",
			"Tanganyikasjøen",
			"Baikalsjøen",
			"Store Bjørnesjø",
			"Malawisjøen",
			"Store Slavesjø",
		],
	},
	{
		q: "Kapteiner på landslaget",
		a: [
			"Thorleif Larsen",
			"Rolf Holmberg",
			"Kjell Kaspersen",
			"Roald Jensen",
			"Kjell Schou-Andreassen",
			"Harald Berg",
			"Arne Larsen Økland",
			"Ole Bjørn Sundgot",
			"Henning Berg",
			"Henning Stensrud",
			"Morten Gamst Pedersen",
			"Brede Hangeland",
			"Steffen Iversen",
			"Ståle Solbakken",
			"Erik Mykland",
			"Tom Høgli",
			"Martin Ødegaard",
			"Stefan Johansen",
			"Jonas Svensson",
			"Joshua King",
			"Per Ciljan Skjelbred",
		],
	},
	{
		q: "Land som har spilt VM finale (menn)",
		a: [
			"Argentina",
			"Brasil",
			"Tyskland",
			"Italia",
			"Frankrike",
			"Uruguay",
			"England",
			"Spania",
			"Nederland",
			"Tsjekkoslovakia",
			"Ungarn",
			"Sverige",
			"Jugoslavia",
			"Vest-Tyskland",
			"Kroatia",
		],
	},
] as SampleQuestion[]
